//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOV
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Proveedor { get; set; }
        public Nullable<bool> TMov { get; set; }
        public Nullable<int> FK_ATAUD { get; set; }
    
        public virtual ATAUD ATAUD { get; set; }
    }
}
